name: Manual Build for Dev or Feature Branches

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build the Docker image from'
        required: true
        default: 'dev'

jobs:
  manual-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the specified branch
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image to GHCR
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
